export const START_GAME = 'START_GAME';
export const INITIALIZE_PIECES = 'INITIALIZE_PIECES';
export const RESTART_GAME = 'RESTART_GAME';
export const PLAYER_PLACE_PIECE = 'PLAYER_PLACE_PIECE';
export const COMPUTER_PLACE_PIECE = 'COMPUTER_PLACE_PIECE';