export const START_GAME = 'START_GAME';
export const INITIALIZE_PIECES = 'INITIALIZE_PIECES';
export const RESTART_GAME = 'RESTART_GAME';
export const PLAYER_INITIALIZE_BOARD = 'PLAYER_INITIALIZE_BOARD';
export const OPPONENT_INITIALIZE_BOARD = 'OPPONENT_INITIALIZE_BOARD';
export const PLAYER_MOVE = 'PLAYER_MOVE';